 export let declaredmenuitems={
    "breakfast": [  { "id": 1, "name": "Puttu and Kadala Curry", "caloriesPerServing": 450, "cookTimeMinutes": 30, "cuisine": "Kerala", "difficulty": "Medium", "image": "https://example.com/puttu-kadala.jpg", "ingredients": ["Rice flour", "Grated coconut", "Black chickpeas", "Onion", "Tomato", "Spices"], "instructions": ["Steam rice flour with grated coconut to make puttu.", "Cook black chickpeas with onion, tomato, and spices to prepare kadala curry.", "Serve hot with banana or pappadam."], "mealType": ["Breakfast"], "prepTimeMinutes": 20, "rating": 4.7, "reviewCount": 120, "servings": 2, "tags": ["Traditional", "Healthy"], "userId": 101 },
      { "id": 2, "name": "Appam with Stew", "caloriesPerServing": 400, "cookTimeMinutes": 35, "cuisine": "Kerala", "difficulty": "Medium", "image": "https://example.com/appam-stew.jpg", "ingredients": ["Rice batter", "Coconut milk", "Vegetables", "Spices"], "instructions": ["Ferment rice batter overnight and cook appams.", "Prepare stew with coconut milk and vegetables.", "Serve hot together."], "mealType": ["Breakfast"], "prepTimeMinutes": 25, "rating": 4.6, "reviewCount": 98, "servings": 2, "tags": ["Soft", "Traditional"], "userId": 102 },
      { "id": 3, "name": "Idiyappam with Egg Curry", "caloriesPerServing": 500, "cookTimeMinutes": 30, "cuisine": "Kerala", "difficulty": "Medium", "image": "https://example.com/idiyappam-egg.jpg", "ingredients": ["Rice flour", "Eggs", "Onion", "Tomato", "Spices"], "instructions": ["Steam rice flour into idiyappam.", "Prepare egg curry with spices and coconut milk.", "Serve together."], "mealType": ["Breakfast"], "prepTimeMinutes": 20, "rating": 4.8, "reviewCount": 130, "servings": 2, "tags": ["Healthy", "Tasty"], "userId": 103 },
      { "id": 4, "name": "Dosa with Chutney and Sambar", "caloriesPerServing": 350, "cookTimeMinutes": 25, "cuisine": "Kerala", "difficulty": "Easy", "image": "https://example.com/dosa-sambar.jpg", "ingredients": ["Rice batter", "Lentils", "Coconut", "Spices"], "instructions": ["Prepare dosa from fermented batter.", "Cook sambar with lentils and vegetables.", "Serve with coconut chutney."], "mealType": ["Breakfast"], "prepTimeMinutes": 15, "rating": 4.9, "reviewCount": 150, "servings": 2, "tags": ["Crispy", "Popular"], "userId": 104 },
      { "id": 5, "name": "Uppumavu with Banana", "caloriesPerServing": 320, "cookTimeMinutes": 15, "cuisine": "Kerala", "difficulty": "Easy", "image": "https://example.com/uppumavu-banana.jpg", "ingredients": ["Semolina", "Mustard seeds", "Green chilies", "Curry leaves", "Banana"], "instructions": ["Roast semolina and cook with spices.", "Serve hot with banana."], "mealType": ["Breakfast"], "prepTimeMinutes": 10, "rating": 4.5, "reviewCount": 110, "servings": 2, "tags": ["Simple", "Quick"], "userId": 105 },
      { "id": 6, "name": "Idli with Chutney and Sambar", "caloriesPerServing": 300, "cookTimeMinutes": 20, "cuisine": "Kerala", "difficulty": "Easy", "image": "https://example.com/idli-sambar.jpg", "ingredients": ["Rice batter", "Lentils", "Coconut", "Spices"], "instructions": ["Steam idlis from fermented batter.", "Prepare sambar with lentils and vegetables.", "Serve with coconut chutney."], "mealType": ["Breakfast"], "prepTimeMinutes": 15, "rating": 4.7, "reviewCount": 120, "servings": 2, "tags": ["Soft", "Healthy"], "userId": 106 }
    ],
    "lunch": [
      { "id": 1, "name": "Kerala Sadhya", "caloriesPerServing": 800, "cookTimeMinutes": 60, "cuisine": "Kerala", "difficulty": "Hard", "image": "https://example.com/kerala-sadhya.jpg", "ingredients": ["Rice", "Sambar", "Avial", "Thoran", "Pappadam", "Payasam"], "instructions": ["Cook rice and prepare various side dishes including sambar, avial, and thoran.", "Serve on a banana leaf with pappadam and payasam.", "Enjoy the traditional Kerala feast."], "mealType": ["Lunch"], "prepTimeMinutes": 40, "rating": 4.9, "reviewCount": 200, "servings": 4, "tags": ["Festive", "Traditional"], "userId": 104 },
      { "id": 2, "name": "Fish Curry Meal", "caloriesPerServing": 700, "cookTimeMinutes": 40, "cuisine": "Kerala", "difficulty": "Medium", "image": "https://example.com/fish-curry-meal.jpg", "ingredients": ["Rice", "Fish", "Coconut", "Spices", "Tamarind"], "instructions": ["Cook rice and prepare spicy fish curry.", "Serve hot with side dishes like thoran and pappadam."], "mealType": ["Lunch"], "prepTimeMinutes": 30, "rating": 4.8, "reviewCount": 150, "servings": 3, "tags": ["Spicy", "Seafood"], "userId": 105 }
    ],
    "specialFoods": [
      { "id": 1, "name": "Kerala Beef Fry", "caloriesPerServing": 600, "cookTimeMinutes": 45, "cuisine": "Kerala", "difficulty": "Medium", "image": "https://example.com/kerala-beef-fry.jpg", "ingredients": ["Beef", "Onion", "Garlic", "Ginger", "Curry leaves", "Spices"], "instructions": ["Marinate beef with spices and rest for 30 minutes.", "Cook until tender, then fry with onions and curry leaves.", "Serve hot with porotta."], "mealType": ["Special"], "prepTimeMinutes": 25, "rating": 4.8, "reviewCount": 150, "servings": 3, "tags": ["Spicy", "Non-Veg"], "userId": 106 },
      { "id": 2, "name": "Malabar Chicken Biryani", "caloriesPerServing": 750, "cookTimeMinutes": 60, "cuisine": "Kerala", "difficulty": "Hard", "image": "https://example.com/malabar-biryani.jpg", "ingredients": ["Basmati rice", "Chicken", "Onion", "Spices", "Yogurt", "Ghee"], "instructions": ["Cook basmati rice separately.", "Prepare flavorful chicken masala and layer with rice.", "Dum cook and serve with raita."], "mealType": ["Special"], "prepTimeMinutes": 35, "rating": 4.9, "reviewCount": 180, "servings": 4, "tags": ["Aromatic", "Biryani"], "userId": 107 }
    ],
    "snacks": [
      { "id": 1, "name": "Parippu Vada", "caloriesPerServing": 250, "cookTimeMinutes": 20, "cuisine": "Kerala", "difficulty": "Easy", "image": "https://example.com/parippu-vada.jpg", "ingredients": ["Chana dal", "Onion", "Green chili", "Curry leaves", "Ginger", "Spices"], "instructions": ["Soak chana dal and grind coarsely.", "Mix with onions, chilies, and spices.", "Shape into patties and deep-fry until golden brown.", "Serve hot with tea."], "mealType": ["Snack"], "prepTimeMinutes": 15, "rating": 4.5, "reviewCount": 90, "servings": 2, "tags": ["Crispy", "Tea-time"], "userId": 107 },
      { "id": 2, "name": "Banana Fry (Pazham Pori)", "caloriesPerServing": 300, "cookTimeMinutes": 15, "cuisine": "Kerala", "difficulty": "Easy", "image": "https://example.com/banana-fry.jpg", "ingredients": ["Ripe banana", "Flour", "Sugar", "Oil"], "instructions": ["Slice bananas and dip in a sweet flour batter.", "Deep-fry until golden and serve hot."], "mealType": ["Snack"], "prepTimeMinutes": 10, "rating": 4.7, "reviewCount": 110, "servings": 2, "tags": ["Sweet", "Quick"], "userId": 108 }
    ]
  }
  
  
  